@startuml
start
:validNodes = new Set();
:VISIBLE = Set(axioma,...,modelo);

while (N1: altri assiomi?) is (sì)
  if (N2: isActive?) then (sì)
    :validNodes.add(axiomId);
  endif
endwhile (no)

while (N3: altri nodi?) is (sì)
  if (N4: validNodes.has?) then (sì)
    #palegreen:continue;
  else (no)
    :nodo = this.nodi.get(nodeId);
    if (N5: nodo esiste?) then (no)
      #palegreen:continue;
    else (sì)
      if (N6: isAxiom?) then (sì)
        #palegreen:continue;
      else (no)
        if (N7: type visible?) then (no)
          #palegreen:continue;
        else (sì)
          if (N8: isSatisfiedBy?) then (sì)
            :validNodes.add(nodeId);
          endif
        endif
      endif
    endif
  endif
endwhile (no)

:return validNodes;
stop
@enduml
